Section "Device"
    Identifier "Meson DRM"
    Driver "modesetting"
    Option "kmsdev" "/dev/dri/card1"
    Option "AccelMethod" "glamor"
    Option "DRI" "3"
    Option "PageFlip" "true"
EndSection

Section "Monitor"
    Identifier "Composite-1"
    Option "Ignore" "true"
EndSection

Section "Monitor"
    Identifier "HDMI-A-1"
    Option "PreferredMode" "1920x1080"
EndSection
